name: Juliet
favicon: null
layout_spectrum: 0.92342
typography_spectrum: 0.81892
title: A Neighborhood Place by Bread + Salt Hospitality
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202720'
    - '#dfe0e4'
    - '#abaca4'
    - '#614b34'
    - '#00784b'
  brandStrength: 0.8125
  lightness: 0.8426026161760092
  saturation: 0.625
  rhythmicContrast: 0.1764468306209892
purpose: []
